# Generated by Django 5.2.12 on 2026-03-24 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(db_index=True, max_length=100)),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('anonymous_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('properties', models.JSONField(default=dict)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('source', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend')], default='backend', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['event_name', 'occurred_at'], name='analytics_a_event_n_aeeca0_idx'), models.Index(fields=['session_id', 'occurred_at'], name='analytics_a_session_1e854d_idx')],
            },
        ),
        migrations.CreateModel(
            name='CartAbandonmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_guest', models.BooleanField(default=False)),
                ('cart_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_count', models.IntegerField()),
                ('checkout_started', models.BooleanField(default=False)),
                ('last_event_at', models.DateTimeField()),
                ('abandoned_at', models.DateTimeField(auto_now_add=True)),
                ('week_of', models.DateField(db_index=True)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abandonment_record', to='cart.cart')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_abandonment_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['is_guest', 'week_of'], name='analytics_c_is_gues_3424cb_idx')],
            },
        ),
    ]
