# Generated by Django 5.2.12 on 2026-03-24 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='skilltag',
            name='curriculum_standard',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
